config/routes.rb
Aretheyintome::Application.routes.draw do
  
  root 'questions#index'

  resources :questions do
    resources :options
  end

  

end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
end

app/models/question.rb
class Question < ActiveRecord::Base
  has_many :options, :dependent => :destroy
  accepts_nested_attributes_for :options, :reject_if => lambda { |a| a[:content].blank? }, :allow_destroy => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/options_controller.rb
class OptionsController < ApplicationController
  before_action :set_option, only: [:show, :edit, :update, :destroy]

  # GET /options
  # GET /options.json
  def index
    @question = Question.find(params[:question_id])
    @options = @question.options
  end

  # GET /options/1
  # GET /options/1.json
  def show
    @question = Question.find(params[:question_id])
  end

  # GET /options/new
  def new
    @question = Question.find(params[:question_id])
    @option = Option.new
  end

  # GET /options/1/edit
  def edit
    @question = Question.find(params[:question_id])
  end

  # POST /options
  # POST /options.json
  def create
    @question = Question.find(params[:question_id])
    @option = Option.new(option_params)

    respond_to do |format|
      if @option.save
        format.html { redirect_to question_options_path(@question), notice: 'Option was successfully created.' }
        format.json { render action: 'show', status: :created, location: @option }
      else
        format.html { render action: 'new' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /options/1
  # PATCH/PUT /options/1.json
  def update
    respond_to do |format|
      if @option.update(option_params)
        format.html { redirect_to question_option_path, notice: 'Option was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @option.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /options/1
  # DELETE /options/1.json
  def destroy
    @option.destroy
    respond_to do |format|
      format.html { redirect_to question_options_path }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_option
      @option = Option.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def option_params
      params.require(:option).permit(:content, :question_id, :value)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :set_question, only: [:show, :edit, :update, :destroy]

  # GET /questions
  # GET /questions.json
  def index
    @questions = Question.all
  end

  # GET /questions/1
  # GET /questions/1.json
  def show
  end

  # GET /questions/new
  def new
    @question = Question.new
    4.times { @question.options.build }
  end

  # GET /questions/1/edit
  def edit
  end

  # POST /questions
  # POST /questions.json
  def create
    @question = Question.new(question_params)

    respond_to do |format|
      if @question.save
        format.html { redirect_to @question, notice: 'Question was successfully created.' }
        format.json { render action: 'show', status: :created, location: @question }
      else
        format.html { render action: 'new' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /questions/1
  # PATCH/PUT /questions/1.json
  def update
    respond_to do |format|
      if @question.update(question_params)
        format.html { redirect_to @question, notice: 'Question was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @question.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /questions/1
  # DELETE /questions/1.json
  def destroy
    @question.destroy
    respond_to do |format|
      format.html { redirect_to questions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_question
      @question = Question.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def question_params
      params.require(:question).permit(:content, options_attributes: [:question_id, :content, :value])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/options_helper.rb
module OptionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/.#_question_options.html.erb
chrismccarthy@Chriss-MacBook-Air-2.local.66407

app/views/layouts/_question_options.html.erb
<div class="field">
    <%= f.hidden_field :question_id, :value=>params[:question_id] %>
    <%= f.label :content, "Option:" %>
    <%= f.text_area :content, :rows => 3 %>
    <%= f.label :value, "Value (between 0-1)" %>
    <%= f.text_field :value, value: number_with_precision(f.object.value, precision: 2) %>
    <%#= f.check_box :_destroy %>
    <%#= f.label :_destroy, "Remove Option" %>
</div>		   	  

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Aretheyintome</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/options/_form.html.erb
<%= form_for([@question, @option]) do |f| %>
  <% if @option.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@option.errors.count, "error") %> prohibited this option from being saved:</h2>

      <ul>
      <% @option.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  
    
    
  <div class="field">
    <%= f.hidden_field :question_id, :value=>params[:question_id] %>
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :value %><br>
    <%= f.text_field :value, value: number_with_precision(f.object.value, precision: 2) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/options/edit.html.erb
<h1>Editing option</h1>

<%= render 'form' %>

<%= link_to 'Show', question_option_path %> |
<%= link_to 'Back', question_options_path %>

app/views/options/index.html.erb
<h1>Listing options</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Value</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @options.each do |option| %>
      <tr>
        <td><%= option.content %></td>
        <td><%= option.value %></td>
        <td><%= link_to 'Show', question_option_path(@question, option) %></td>
        <td><%= link_to 'Edit', edit_question_option_path(@question, option) %></td>
        <td><%= link_to 'Destroy', question_option_path(@question, option), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Option', new_question_option_path %> |
<%= link_to 'Back to Question', question_path(@question) %>

app/views/options/new.html.erb
<h1>New option</h1>

<%= render 'form' %>

<%= link_to 'Back', question_options_path %>

app/views/options/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @option.content %>
</p>

<p>
  <strong>Value:</strong>
  <%= @option.value %>
</p>

<%= link_to 'Edit', edit_question_option_path(@question, @option) %> |
<%= link_to 'Back', question_options_path %>

app/views/questions/_edit_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content, :rows => 6 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/_form.html.erb
<%= form_for(@question) do |f| %>
  <% if @question.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@question.errors.count, "error") %> prohibited this question from being saved:</h2>

      <ul>
      <% @question.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'edit_form' %>

<%= link_to 'Show Question and Options', @question %> |
<%= link_to 'Edit and Add Question Options', question_options_path(@question) %>

app/views/questions/index.html.erb
<h1>Listing questions</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.content %></td>
        <td><%= link_to 'Show', question %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Question', new_question_path %>

app/views/questions/new.html.erb
<h1>New question</h1>

<%= render 'form' %>

<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>


<h1><%= @question.content %></h1>
  
  <% if @question.options %>
    <% @question.options.each do |option| %>
      <ul>
	<li><%= option.content %></li>
      </ul>
      <% end %>
      <%= link_to 'Back to Question List', questions_path %> |
      <%= link_to 'Edit Question', edit_question_path(@question) %> |
      <%= link_to 'Edit and Add Options', question_options_path(@question) %>
    <% else %>
      <%= link_to 'Edit', edit_question_path(@question) %> |
      <%= link_to 'New Option', new_question_option_path(@question) %>
      <%= link_to 'Back', questions_path %>
    <% end %>